### ISSUE TITLE
Another feature request 

### ISSUE THREAD

**Issue by CrimsonFury82** [DeedleFake/zero-hour-configuration-solver#4]
Couple of UI tweaks that would really help mobile users. 
1) Change the "found" UI text to display the location instead (e.g. "Red 5").
2) Move the lock/undo/reset buttons above the map.

This would allow mobile users to see the answer and update progress without having to scroll up and down between every input, allowing much quicker entering of codes.

**Comment by gutoandreollo** [comment]
> Change the "found" UI text to display the location instead (e.g. "Red 5").

A different suggestion: Have it either say the actual result ("Red 5", "Blue 3", etc) or "Console readout required" or something like this. This way, the one person calling the combination has a single thing to read on voice for the runners to act on.

**Comment by Sannemen** [comment]
> Change the "found" UI text to display the location instead (e.g. "Red 5").

Better yet, have it either say the console ("Red 5", "Blue 1", etc) or "Console readout needed" (or something to that effect). That way, the person manning the main console has only a single thing to read on voice for the people running activating the 47 consoles.

**Comment by CrimsonFury82** [comment]
That would be great :)

**Comment by DeedleFake** [comment]
1. I actually thought of that yesterday but hadn't had time to implement it yet. Sure.
2. I like that. I've been trying to figure out ways to make the scrolling up and down less annoying on mobile, such as hiding the instructions in a modal that's displayed with a button.

**Comment by DeedleFake** [comment]
![Screenshot_20190522-112057](https://user-images.githubusercontent.com/326750/58186977-e2d9df00-7c83-11e9-8dfb-71865547a45d.png)

This now just barely fits on a single screen on my 1080x1920 Android phone.
